### PR TITLE
Upgrade to Gradle 3.0

### PR DESCRIPTION
**Pull request by janschaefer**

### CODE REVIEW

**Comment by Airblader** [comment]
So JGiven is now dropping support for Java 6?

**Comment by janschaefer** [comment]
Hehe, no. It will still be built for Java 6, but not using Java 6 for building. This introduces a small risk of accidentally using a non-JDK6 API, but as long as I configure IntelliJ correctly, this shouldn't happen either.

**Comment by Airblader** [comment]
OK. :-)

**Comment by ahus1** [comment]
So be extra sure that you use only Java 6 APIs (not only Java 6 Syntax) have a look at http://www.mojohaus.org/animal-sniffer/.

**Comment by janschaefer** [comment]
Thanks @ahus1 for the hint. I will have a look at that!

**Comment by janschaefer** [comment]
Thanks again @ahus1, works like a charm! :-)

**Pull request merged**
