### PR TITLE
Apply plugin java-library for dependency management.

### PR DESCRIPTION
**Pull request by mustaine**
As part of updating gradle, required to fix version for `gradle-animalsniffer-plugin`

### CODE REVIEW

**Comment by mustaine** [comment]
@janschaefer looks like the annotation `@FailingOnPurpose` is not working properly. Could you check it?

**Comment by janschaefer** [comment]
There seems to be a problem with the JGiven Gradle plugin as it uses an internal API.

**Comment by mustaine** [comment]
No worries @janschaefer as I need to update the gradle plugin.

**Comment by mustaine** [comment]
I had some issues to make it pass. The problem was that in the main `build.gradle` the task `jgivenHtml5Report` only use `testCompile`.

**Comment by janschaefer** [comment]
Cool. Thanks!

**Pull request merged**
