### PR TITLE
implemented nested steps #17 (+ text report only)

### PR DESCRIPTION
**Pull request by albertofaci**
Hello, this is an attempt to support nested steps.

I had to change a few things around ScenarioModelBuilder to keep a stack of steps so we can add a nested step to the right parent and supporting multilevel nesting. 

As for the report, I have just done it for the plain text report. Note that the nested steps are for report purposes only, i.e. the step status, duration, attachments, etc, are really kept at the top level only. Otherwise it gets too complicated.
If this is accepted, a separate issue should be created for html5 report maybe with a collapsible widget

### CODE REVIEW

**Comment by albertofaci** [comment]
Hiya, any comments or suggestions about this?

**Comment by janschaefer** [comment]
Hi, sorry, I already worked a bit on it, but did not came very far yet due to lack of time. You can have a look at the new branch `nested-steps`. I changed a bit the appearence of the console report and I also would like to integrate the correct execution status on the sub steps. I also would like to integrate it into the html report

**Comment by janschaefer** [comment]
I slightly adapted your implementation and also took the chance to refactor the method intercepting code. I also changed a bit the way the nested steps are printed. In particular, I believe the fail status should be printed after the nested step that actually failed.

**Comment by albertofaci** [comment]
Nice one, thank you, Jan!

As far as I can see the failed status will appear only on the parent top most state.

Current
```
Given something with nested steps that fails (failed)
 |  Given something
 |  And another thing
 |  And something else that fails
When something happens (skipped)
Then something has happen (skipped)
something else not (skipped)
```

whereas the following would be desirable?

```
Given something with nested steps that fails (failed)
 |  Given something (passed)
 |  And another thing (failed)
 |  And something else that fails (skipped)
When something happens (skipped)
Then something has happen (skipped)
something else not (skipped)
```

**Comment by janschaefer** [comment]
With the current implementation the parent step will not be shown as failed. But I agree that this makes sense. I will change that.

**Comment by janschaefer** [comment]
I did a first HTML report implementation. Collapsing is still missing though. What do you think? 

nested-steps

**Comment by albertofaci** [comment]
well done, that looks brilliant!

**Pull request merged**
