### PR TITLE
Scenarios can be written in Spanish

### PR DESCRIPTION
**Pull request by elenagarcia5**
A little contribution to create JGiven scenarios in Spanish

### CODE REVIEW

**Comment by janschaefer** [comment]
Really nice :-). ¡Muchas Gracias Elena! 
I still have to think how to make translations easier. Currently too much code has to be adapted, but I am not sure yet how to do that.

**Comment by elenagarcia5** [comment]
You're welcome! I agree with you, it would be great if JGiven had a simpler way to make translations. I will also think about that.

**Comment by janschaefer** [comment]
@Airblader amazing idea!

**Comment by janschaefer** [comment]
Created a ticket for that: #285

**Pull request merged**
