### PR TITLE
Issue282 - Deprecated Case Annotation

### PR DESCRIPTION
**Pull request by cirquit**
* deprecated the case annotation for `OrdinalCaseAnnotataion` as described in #282 
* added documentation
* because the documentation used asciidoc examples, I also implemented asciidoc parsing for case descriptions

### CODE REVIEW

**Comment by cirquit** [comment]
This code produces this following ascii-document.
ordinal-desc-coffe
ordinal-desc-asciidoc

**Comment by janschaefer** [comment]
Ok. Looks good so far, the only thing: I don't like the name OrdinalCaseDescription :-). You immediately wonder what is a normal CaseDescription which is deprecated. Maybe we find another name that is as general as CaseDescription?

**Comment by cirquit** [comment]
From the top of my head:

- `TableDescription`
- `RowDescription`
- `ItemDescription`
- `CaseDataDescription`
- `UnitDescription`
- `ElementDescription`

**Comment by cirquit** [comment]
As discussed offline, before merging I want to remove all ambiguity from CaseDescription AND As Annotation, because it does not allow mixing of placeholders like the ExtendedDescription.

- [X] Add `$argumentName` parsing for StepFormatter (As Annotation)
- [ ] Add `$argumentName` parsing for CaseDescription
- [ ] Add single `$` count for StepFormatter
- [ ] Add single `$` count for CaseDescription
- [ ] Add tests for StepFormatter
- [ ] Add tests for CaseDescription

**Comment by cirquit** [comment]
Still TODO:

- [ ] write documentation

**Comment by janschaefer** [comment]
What about one of the following names: 
* CaseSummary
* CaseName
* CaseTitle

**Comment by cirquit** [comment]
CaseSummary seems nice because of the __describing__ nature. CaseName and CaseTitle seem to be too specific.

**Comment by janschaefer** [comment]
Also an option woud be CaseAs, because it would be consistent to the As annotation

**Pull request merged**
