### PR TITLE
appended changes since 8.01.2020 to changelog

### PR DESCRIPTION
**Pull request by l-1squared**
Signed-off-by: l-1squared <30831153+l-1squared@users.noreply.github.com>

### CODE REVIEW

**Comment by l-1squared** [comment]
> Why should Java 9 not be supported anymore? This would be quite bad.

I basically went by this commit and its message: https://github.com/TNG/JGiven/commit/b8409a912563c497129e2a4c21303a80295f9631

**Comment by jsalinaspolo** [comment]
Java 9 is supported, just we are not building in Java9 as we build in Java8, 11 and 13

**Comment by jsalinaspolo** [comment]
Should we use links to the contributors instead of plain text? It would fix if a contributor changes the username - @jsalinaspolo instead of jsalinaspolo ?

**Comment by l-1squared** [comment]
> Should we use links to the contributors instead of plain text? It would fix if a contributor changes the username - @jsalinaspolo instead of jsalinaspolo 

Ah, a misunderstanding on my side. I will change the text accordingly :) And try out the user tags.

**Comment by l-1squared** [comment]
> Should we use links to the contributors instead of plain text? It would fix if a contributor changes the username - @jsalinaspolo instead of jsalinaspolo ?

according to https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/changing-your-github-username, it seems that username links are not protected against a username change. the @jsalinaspolo  you can use here also seem to effectively be converted to a link to your user profile. As such a see no possibility for us to protect the changelog document against username changes.

**Comment by l-1squared** [comment]
@janschaefer is there still something missing?

**Pull request merged**
